import type { SlotGameConfig } from '../../utils/types';

export const classicFruitsConfig: SlotGameConfig = {
  id: 'classic-fruits',
  name: 'Classic Fruits',
  description: 'A retro 3-reel fruit machine with simple paylines. No frills, just classic fun!',
  reels: 3,
  rows: 3,
  symbols: [
    { id: 'cherry', name: 'Cherry', svg: '\ud83c\udf52', color: '#e74c3c' },
    { id: 'lemon', name: 'Lemon', svg: '\ud83c\udf4b', color: '#f1c40f' },
    { id: 'orange', name: 'Orange', svg: '\ud83c\udf4a', color: '#e67e22' },
    { id: 'plum', name: 'Plum', svg: '\ud83c\udf51', color: '#9b59b6' },
    { id: 'grape', name: 'Grape', svg: '\ud83c\udf47', color: '#8e44ad' },
    { id: 'watermelon', name: 'Watermelon', svg: '\ud83c\udf49', color: '#27ae60' },
    { id: 'bell', name: 'Bell', svg: '\ud83d\udd14', color: '#f39c12' },
    { id: 'seven', name: 'Lucky 7', svg: '7\ufe0f\u20e3', color: '#e74c3c' },
  ],
  paylines: [
    { id: 1, positions: [0, 0, 0], color: '#e74c3c' },
    { id: 2, positions: [1, 1, 1], color: '#3498db' },
    { id: 3, positions: [2, 2, 2], color: '#2ecc71' },
    { id: 4, positions: [0, 1, 2], color: '#f39c12' },
    { id: 5, positions: [2, 1, 0], color: '#9b59b6' },
  ],
  payoutTable: [
    { symbolId: 'cherry', count: 2, multiplier: 2 },
    { symbolId: 'cherry', count: 3, multiplier: 5 },
    { symbolId: 'lemon', count: 3, multiplier: 4 },
    { symbolId: 'orange', count: 3, multiplier: 6 },
    { symbolId: 'plum', count: 3, multiplier: 8 },
    { symbolId: 'grape', count: 3, multiplier: 10 },
    { symbolId: 'watermelon', count: 3, multiplier: 12 },
    { symbolId: 'bell', count: 2, multiplier: 5 },
    { symbolId: 'bell', count: 3, multiplier: 20 },
    { symbolId: 'seven', count: 2, multiplier: 10 },
    { symbolId: 'seven', count: 3, multiplier: 50 },
  ],
  minBet: 10,
  maxBet: 20000,
  betStep: 10,
  features: [],
  thumbnail: '\ud83c\udf52',
  themeColor: '#e74c3c',
  reelWeights: {
    cherry: 15, lemon: 12, orange: 12, plum: 10,
    grape: 10, watermelon: 8, bell: 5, seven: 3,
  },
};
